use extended COIN_HAS_MODULE macro

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23631,6 +23631,7 @@ esac
 fi
 
 if test "x$use_blas" = xBUILD ; then
+  if test -d ../ThirdParty/Blas ; then
 
 echo "$as_me:$LINENO: checking for COIN-OR module Blas" >&5
 echo $ECHO_N "checking for COIN-OR module Blas... $ECHO_C" >&6
@@ -23769,8 +23770,87 @@ fi
 
     PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
   else
-    echo "$as_me:$LINENO: result: skipped check via pkg-config" >&5
-echo "${ECHO_T}skipped check via pkg-config" >&6
+    #if 4th argument is given, try fallback - whereby we take the first word from coinblas as basename for the .pc file
+
+if test x$coin_has_blas != "xyes" ; then
+
+
+
+coin_has_blas=notGiven
+
+# check if user wants to skip module in any case
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Blas"; then
+      coin_has_blas=skipping
+    fi
+  done
+fi
+
+BLAS_LIBS=
+BLAS_CFLAGS=
+BLAS_DATA=
+
+
+if test $coin_has_blas != "skipping" ; then
+  # if the project is available and configured, then a project-uninstalled.pc file should have been created
+  if test -r ../ThirdParty/Blas/coinblas-uninstalled.pc ; then
+    # read CFLAGS and LIBS from m4_bpatsubst(coinblas, [ .*], [])-uninstalled.pc file
+    # add CYGPATH_W cludge into include flags
+    # replace -L${libdir} by absolute path to build directory in linker flags
+    # we assume that the build directory is ../ThirdParty/Blas/src if this directory exists, otherwise we assume that it is ../ThirdParty/Blas
+    BLAS_CFLAGS=`sed -n -e 's/Cflags://' -e 's/-I\(^ *\)/-I\`${CYGPATH_W} \1\`/gp' ../ThirdParty/Blas/coinblas-uninstalled.pc`
+    projectlibs=`sed -n -e 's/Libs://' -e 's/-L\${libdir}//p' ../ThirdParty/Blas/coinblas-uninstalled.pc`
+    if test "x$projectlibs" != x ; then
+      if test -d ../ThirdParty/Blas/src ; then
+        BLAS_LIBS="-L`cd ../ThirdParty/Blas/src; pwd` $projectlibs"
+      else
+        BLAS_LIBS="-L`cd ../ThirdParty/Blas; pwd` $projectlibs"
+      fi
+    else
+      BLAS_LIBS=`sed -n -e 's/Libs://p' ../ThirdParty/Blas/coinblas-uninstalled.pc`
+    fi
+    BLAS_DATA=`sed -n -e 's/datadir=//gp' ../ThirdParty/Blas/coinblas-uninstalled.pc`
+
+    ADDLIBS="$ADDLIBS $BLAS_LIBS"
+       REQUIREDPACKAGES="$REQUIREDPACKAGES coinblas"
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_BLAS 1
+_ACEOF
+
+
+
+    coin_has_blas=yes
+    echo "$as_me:$LINENO: result: ../ThirdParty/Blas" >&5
+echo "${ECHO_T}../ThirdParty/Blas" >&6
+  else
+    echo "$as_me:$LINENO: result: $coin_has_blas" >&5
+echo "${ECHO_T}$coin_has_blas" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: skipping" >&5
+echo "${ECHO_T}skipping" >&6
+fi
+
+#if user did not disable setting of makefile conditional, do it
+
+
+if test $coin_has_blas != notGiven &&
+                test $coin_has_blas != skipping; then
+  COIN_HAS_BLAS_TRUE=
+  COIN_HAS_BLAS_FALSE='#'
+else
+  COIN_HAS_BLAS_TRUE='#'
+  COIN_HAS_BLAS_FALSE=
+fi
+
+
+fi
+
+
   fi
 
 else
@@ -23815,6 +23895,271 @@ fi
 
 
 
+  elif test -d ../Blas ; then
+
+echo "$as_me:$LINENO: checking for COIN-OR module Blas" >&5
+echo $ECHO_N "checking for COIN-OR module Blas... $ECHO_C" >&6
+
+coin_has_blas=notGiven
+
+# check if user wants to skip module in any case
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Blas"; then
+      coin_has_blas=skipping
+    fi
+  done
+fi
+
+BLAS_LIBS=
+BLAS_CFLAGS=
+BLAS_DATA=
+
+
+
+
+
+#check if user provided LIBS, CFLAGS, and DATA for module
+if test $coin_has_blas != skipping; then
+
+
+# Check whether --with-m4_tolower(Blas)-lib or --without-m4_tolower(Blas)-lib was given.
+if test "${with_blas_lib+set}" = set; then
+  withval="$with_blas_lib"
+  coin_has_blas=yes
+       BLAS_LIBS="$withval"
+       ADDLIBS="$ADDLIBS $withval"
+
+fi;
+
+
+# Check whether --with-m4_tolower(Blas)-incdir or --without-m4_tolower(Blas)-incdir was given.
+if test "${with_blas_incdir+set}" = set; then
+  withval="$with_blas_incdir"
+  coin_has_blas=yes
+     BLAS_CFLAGS="-I`${CYGPATH_W} $withval`"
+fi;
+
+
+# Check whether --with-m4_tolower(Blas)-datadir or --without-m4_tolower(Blas)-datadir was given.
+if test "${with_blas_datadir+set}" = set; then
+  withval="$with_blas_datadir"
+  coin_has_blas=yes
+     BLAS_DATA="$withval"
+fi;
+fi
+
+if test $coin_has_blas = notGiven; then
+  if test -n "$PKG_CONFIG" ; then
+    # assemble search path for pkg-config
+    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
+
+    # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
+    # best would actually to use ${libdir}, since .pc files get installed into ${libdir}/pkgconfig,
+    # unfortunately, ${libdir} expands to ${exec_prefix}/lib and ${exec_prefix} to ${prefix}...
+    if test -d "${prefix}"; then
+      PKG_CONFIG_PATH="${prefix}/lib/pkgconfig:$PKG_CONFIG_PATH"
+    fi
+
+
+# Check whether --with-coin-instdir or --without-coin-instdir was given.
+if test "${with_coin_instdir+set}" = set; then
+  withval="$with_coin_instdir"
+  if test -d "$withval"; then : ; else
+         { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
+echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
+   { (exit 1); exit 1; }; }
+       fi
+       PKG_CONFIG_PATH="$withval/lib/pkgconfig:$PKG_CONFIG_PATH"
+
+fi;
+
+    # in a classic setup, we want to find uninstalled projects
+    # their (relative) location is written to coin_subdirs.txt by the configure in the project base directory
+    # unfortunately, if the user set prefix, then we do not know where the project base directory is located
+    # but it is likely to be either .. (if we are a usual coin project) or ../.. (if we are a unusual coin project like ThirdParty or Data)
+    if test -e ../coin_subdirs.txt ; then
+      for i in `cat ../coin_subdirs.txt` ; do
+        PKG_CONFIG_PATH="../$i:$PKG_CONFIG_PATH"
+      done
+    fi
+
+    if test -e ../../coin_subdirs.txt ; then
+      for i in `cat ../../coin_subdirs.txt` ; do
+        PKG_CONFIG_PATH="../../$i:$PKG_CONFIG_PATH"
+      done
+    fi
+
+    # let pkg-config do it's magic
+    # need to export variable to be sure that the following pkg-config gets these values
+    export PKG_CONFIG_PATH
+
+
+
+if test -n "$PKG_CONFIG" ; then
+  if $PKG_CONFIG --exists "coinblas"; then
+    BLAS_VERSIONS="`$PKG_CONFIG --modversion coinblas 2>/dev/null`"
+     cflags=`$PKG_CONFIG --cflags "coinblas" 2>/dev/null`
+    # pkg-config cannot handle spaces, so CYGPATH_W cannot be put into .pc files
+	# thus, we modify the cflags extracted from pkg-config by putting CYGPATH_W behind -I's
+	# but only do this if is not trivial
+    if test "$CYGPATH_W" != "echo" ; then
+      # need to put into brackets since otherwise autoconf replaces the brackets in the sed command
+	  cflags=`echo $cflags | sed -e 's/-I\([^ ]*\)/-I\`${CYGPATH_W} \1\`/g'`
+	fi
+    BLAS_CFLAGS="$cflags"
+    BLAS_LIBS=`$PKG_CONFIG --libs "coinblas" 2>/dev/null`
+    BLAS_DATA=`$PKG_CONFIG --variable=datadir "coinblas" 2>/dev/null`
+     coin_has_blas=yes
+        echo "$as_me:$LINENO: result: yes: $BLAS_VERSIONS" >&5
+echo "${ECHO_T}yes: $BLAS_VERSIONS" >&6
+        REQUIREDPACKAGES="$REQUIREDPACKAGES coinblas"
+
+
+  else
+    BLAS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors coinblas`
+      coin_has_blas=notGiven
+        echo "$as_me:$LINENO: result: not given: $BLAS_PKG_ERRORS" >&5
+echo "${ECHO_T}not given: $BLAS_PKG_ERRORS" >&6
+
+  fi
+else
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Blas without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module Blas without pkg-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+
+    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
+  else
+    #if 4th argument is given, try fallback - whereby we take the first word from coinblas as basename for the .pc file
+
+if test x$coin_has_blas != "xyes" ; then
+
+
+
+coin_has_blas=notGiven
+
+# check if user wants to skip module in any case
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Blas"; then
+      coin_has_blas=skipping
+    fi
+  done
+fi
+
+BLAS_LIBS=
+BLAS_CFLAGS=
+BLAS_DATA=
+
+
+if test $coin_has_blas != "skipping" ; then
+  # if the project is available and configured, then a project-uninstalled.pc file should have been created
+  if test -r ../Blas/coinblas-uninstalled.pc ; then
+    # read CFLAGS and LIBS from m4_bpatsubst(coinblas, [ .*], [])-uninstalled.pc file
+    # add CYGPATH_W cludge into include flags
+    # replace -L${libdir} by absolute path to build directory in linker flags
+    # we assume that the build directory is ../Blas/src if this directory exists, otherwise we assume that it is ../Blas
+    BLAS_CFLAGS=`sed -n -e 's/Cflags://' -e 's/-I\(^ *\)/-I\`${CYGPATH_W} \1\`/gp' ../Blas/coinblas-uninstalled.pc`
+    projectlibs=`sed -n -e 's/Libs://' -e 's/-L\${libdir}//p' ../Blas/coinblas-uninstalled.pc`
+    if test "x$projectlibs" != x ; then
+      if test -d ../Blas/src ; then
+        BLAS_LIBS="-L`cd ../Blas/src; pwd` $projectlibs"
+      else
+        BLAS_LIBS="-L`cd ../Blas; pwd` $projectlibs"
+      fi
+    else
+      BLAS_LIBS=`sed -n -e 's/Libs://p' ../Blas/coinblas-uninstalled.pc`
+    fi
+    BLAS_DATA=`sed -n -e 's/datadir=//gp' ../Blas/coinblas-uninstalled.pc`
+
+    ADDLIBS="$ADDLIBS $BLAS_LIBS"
+       REQUIREDPACKAGES="$REQUIREDPACKAGES coinblas"
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_BLAS 1
+_ACEOF
+
+
+
+    coin_has_blas=yes
+    echo "$as_me:$LINENO: result: ../Blas" >&5
+echo "${ECHO_T}../Blas" >&6
+  else
+    echo "$as_me:$LINENO: result: $coin_has_blas" >&5
+echo "${ECHO_T}$coin_has_blas" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: skipping" >&5
+echo "${ECHO_T}skipping" >&6
+fi
+
+#if user did not disable setting of makefile conditional, do it
+
+
+if test $coin_has_blas != notGiven &&
+                test $coin_has_blas != skipping; then
+  COIN_HAS_BLAS_TRUE=
+  COIN_HAS_BLAS_FALSE='#'
+else
+  COIN_HAS_BLAS_TRUE='#'
+  COIN_HAS_BLAS_FALSE=
+fi
+
+
+fi
+
+
+  fi
+
+else
+  echo "$as_me:$LINENO: result: $coin_has_blas" >&5
+echo "${ECHO_T}$coin_has_blas" >&6
+fi
+
+if test $coin_has_blas != skipping &&
+   test $coin_has_blas != notGiven ; then
+  if test 0 = 1 ; then  #change this test to enable a bit of debugging output
+  if test -n "$BLAS_CFLAGS" ; then
+    { echo "$as_me:$LINENO: Blas CFLAGS are $BLAS_CFLAGS" >&5
+echo "$as_me: Blas CFLAGS are $BLAS_CFLAGS" >&6;}
+  fi
+  if test -n "$BLAS_LIBS" ; then
+    { echo "$as_me:$LINENO: Blas LIBS   are $BLAS_LIBS" >&5
+echo "$as_me: Blas LIBS   are $BLAS_LIBS" >&6;}
+  fi
+  if test -n "$BLAS_DATA" ; then
+    { echo "$as_me:$LINENO: Blas DATA   is  $BLAS_DATA" >&5
+echo "$as_me: Blas DATA   is  $BLAS_DATA" >&6;}
+  fi
+  fi
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_BLAS 1
+_ACEOF
+
+fi
+
+# Define the Makefile conditional
+
+
+if test $coin_has_blas != notGiven &&
+                test $coin_has_blas != skipping; then
+  COIN_HAS_BLAS_TRUE=
+  COIN_HAS_BLAS_FALSE='#'
+else
+  COIN_HAS_BLAS_TRUE='#'
+  COIN_HAS_BLAS_FALSE=
+fi
+
+
+
+  fi
 
 elif test "x$use_blas" != x && test "$use_blas" != no; then
   coin_has_blas=yes
@@ -23853,82 +24198,6 @@ else
 fi
 
 fi
-
-#call fallback in case the previous failed, maybe because pkg-config was not available
-
-if test x$coin_has_blas != "xyes" ; then
-echo "$as_me:$LINENO: checking for COIN-OR module Blas (fallback)" >&5
-echo $ECHO_N "checking for COIN-OR module Blas (fallback)... $ECHO_C" >&6
-
-coin_has_blas=notGiven
-
-# check if user wants to skip module in any case
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = "Blas"; then
-      coin_has_blas=skipping
-    fi
-  done
-fi
-
-BLAS_LIBS=
-BLAS_CFLAGS=
-BLAS_DATA=
-
-
-if test $coin_has_blas != "skipping" ; then
-  # if the project is available and configured, then a project-uninstalled.pc file should have been created
-  if test -r ../ThirdParty/Blas/coinblas-uninstalled.pc ; then
-    # read CFLAGS and LIBS from coinblas-uninstalled.pc file
-    # add CYGPATH_W cludge into include flags
-    # replace -L${libdir} by absolute path to build directory in linker flags
-    # we assume that the build directory is ../ThirdParty/Blas/src if this directory exists, otherwise we assume that it is ../ThirdParty/Blas
-    BLAS_CFLAGS=`sed -n -e 's/Cflags://' -e 's/-I\([^ ]*\)/-I\`${CYGPATH_W} \1\`/gp' ../ThirdParty/Blas/coinblas-uninstalled.pc`
-    projectlibs=`sed -n -e 's/Libs://' -e 's/-L\${libdir}//p' ../ThirdParty/Blas/coinblas-uninstalled.pc`
-    if test "x$projectlibs" != x ; then
-      if test -d ../ThirdParty/Blas/src ; then
-        BLAS_LIBS="-L`cd ../ThirdParty/Blas/src; pwd` $projectlibs"
-      else
-        BLAS_LIBS="-L`cd ../ThirdParty/Blas; pwd` $projectlibs"
-      fi
-    else
-      BLAS_LIBS=`sed -n -e 's/Libs://p' ../ThirdParty/Blas/coinblas-uninstalled.pc`
-    fi
-    BLAS_DATA=`sed -n -e 's/datadir=//gp' ../ThirdParty/Blas/coinblas-uninstalled.pc`
-
-    ADDLIBS="$ADDLIBS $BLAS_LIBS"
-       REQUIREDPACKAGES="$REQUIREDPACKAGES coinblas"
-
-
-
-cat >>confdefs.h <<\_ACEOF
-#define COIN_HAS_BLAS 1
-_ACEOF
-
-
-
-    coin_has_blas=yes
-  fi
-fi
-
-#if user did not disable setting of makefile conditional, do it
-
-
-if test $coin_has_blas != notGiven &&
-                test $coin_has_blas != skipping; then
-  COIN_HAS_BLAS_TRUE=
-  COIN_HAS_BLAS_FALSE='#'
-else
-  COIN_HAS_BLAS_TRUE='#'
-  COIN_HAS_BLAS_FALSE=
-fi
-
-
-
-echo "$as_me:$LINENO: result: $coin_has_blas" >&5
-echo "${ECHO_T}$coin_has_blas" >&6
-fi
-
 
 
 
@@ -24069,8 +24338,87 @@ fi
 
     PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
   else
-    echo "$as_me:$LINENO: result: skipped check via pkg-config" >&5
-echo "${ECHO_T}skipped check via pkg-config" >&6
+    #if 4th argument is given, try fallback - whereby we take the first word from coinmetis >= 4.0 as basename for the .pc file
+
+if test x$coin_has_metis != "xyes" ; then
+
+
+
+coin_has_metis=notGiven
+
+# check if user wants to skip module in any case
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Metis"; then
+      coin_has_metis=skipping
+    fi
+  done
+fi
+
+METIS_LIBS=
+METIS_CFLAGS=
+METIS_DATA=
+
+
+if test $coin_has_metis != "skipping" ; then
+  # if the project is available and configured, then a project-uninstalled.pc file should have been created
+  if test -r ../Metis/coinmetis-uninstalled.pc ; then
+    # read CFLAGS and LIBS from m4_bpatsubst(coinmetis >= 4.0, [ .*], [])-uninstalled.pc file
+    # add CYGPATH_W cludge into include flags
+    # replace -L${libdir} by absolute path to build directory in linker flags
+    # we assume that the build directory is ../Metis/src if this directory exists, otherwise we assume that it is ../Metis
+    METIS_CFLAGS=`sed -n -e 's/Cflags://' -e 's/-I\(^ *\)/-I\`${CYGPATH_W} \1\`/gp' ../Metis/coinmetis-uninstalled.pc`
+    projectlibs=`sed -n -e 's/Libs://' -e 's/-L\${libdir}//p' ../Metis/coinmetis-uninstalled.pc`
+    if test "x$projectlibs" != x ; then
+      if test -d ../Metis/src ; then
+        METIS_LIBS="-L`cd ../Metis/src; pwd` $projectlibs"
+      else
+        METIS_LIBS="-L`cd ../Metis; pwd` $projectlibs"
+      fi
+    else
+      METIS_LIBS=`sed -n -e 's/Libs://p' ../Metis/coinmetis-uninstalled.pc`
+    fi
+    METIS_DATA=`sed -n -e 's/datadir=//gp' ../Metis/coinmetis-uninstalled.pc`
+
+    ADDLIBS="$ADDLIBS $METIS_LIBS"
+       REQUIREDPACKAGES="$REQUIREDPACKAGES coinmetis"
+
+
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_METIS 1
+_ACEOF
+
+
+
+    coin_has_metis=yes
+    echo "$as_me:$LINENO: result: ../Metis" >&5
+echo "${ECHO_T}../Metis" >&6
+  else
+    echo "$as_me:$LINENO: result: $coin_has_metis" >&5
+echo "${ECHO_T}$coin_has_metis" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: skipping" >&5
+echo "${ECHO_T}skipping" >&6
+fi
+
+#if user did not disable setting of makefile conditional, do it
+
+
+if test $coin_has_metis != notGiven &&
+                test $coin_has_metis != skipping; then
+  COIN_HAS_METIS_TRUE=
+  COIN_HAS_METIS_FALSE='#'
+else
+  COIN_HAS_METIS_TRUE='#'
+  COIN_HAS_METIS_FALSE=
+fi
+
+
+fi
+
+
   fi
 
 else
@@ -24114,80 +24462,6 @@ else
 fi
 
 
-
-
-if test x$coin_has_metis != "xyes" ; then
-echo "$as_me:$LINENO: checking for COIN-OR module Metis (fallback)" >&5
-echo $ECHO_N "checking for COIN-OR module Metis (fallback)... $ECHO_C" >&6
-
-coin_has_metis=notGiven
-
-# check if user wants to skip module in any case
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = "Metis"; then
-      coin_has_metis=skipping
-    fi
-  done
-fi
-
-METIS_LIBS=
-METIS_CFLAGS=
-METIS_DATA=
-
-
-if test $coin_has_metis != "skipping" ; then
-  # if the project is available and configured, then a project-uninstalled.pc file should have been created
-  if test -r ../Metis/coinmetis-uninstalled.pc ; then
-    # read CFLAGS and LIBS from coinmetis-uninstalled.pc file
-    # add CYGPATH_W cludge into include flags
-    # replace -L${libdir} by absolute path to build directory in linker flags
-    # we assume that the build directory is ../Metis/src if this directory exists, otherwise we assume that it is ../Metis
-    METIS_CFLAGS=`sed -n -e 's/Cflags://' -e 's/-I\([^ ]*\)/-I\`${CYGPATH_W} \1\`/gp' ../Metis/coinmetis-uninstalled.pc`
-    projectlibs=`sed -n -e 's/Libs://' -e 's/-L\${libdir}//p' ../Metis/coinmetis-uninstalled.pc`
-    if test "x$projectlibs" != x ; then
-      if test -d ../Metis/src ; then
-        METIS_LIBS="-L`cd ../Metis/src; pwd` $projectlibs"
-      else
-        METIS_LIBS="-L`cd ../Metis; pwd` $projectlibs"
-      fi
-    else
-      METIS_LIBS=`sed -n -e 's/Libs://p' ../Metis/coinmetis-uninstalled.pc`
-    fi
-    METIS_DATA=`sed -n -e 's/datadir=//gp' ../Metis/coinmetis-uninstalled.pc`
-
-    ADDLIBS="$ADDLIBS $METIS_LIBS"
-       REQUIREDPACKAGES="$REQUIREDPACKAGES coinmetis"
-
-
-
-cat >>confdefs.h <<\_ACEOF
-#define COIN_HAS_METIS 1
-_ACEOF
-
-
-
-    coin_has_metis=yes
-  fi
-fi
-
-#if user did not disable setting of makefile conditional, do it
-
-
-if test $coin_has_metis != notGiven &&
-                test $coin_has_metis != skipping; then
-  COIN_HAS_METIS_TRUE=
-  COIN_HAS_METIS_FALSE='#'
-else
-  COIN_HAS_METIS_TRUE='#'
-  COIN_HAS_METIS_FALSE=
-fi
-
-
-
-echo "$as_me:$LINENO: result: $coin_has_metis" >&5
-echo "${ECHO_T}$coin_has_metis" >&6
-fi
 
 
 if test "$coin_has_metis" = yes; then
@@ -24590,6 +24864,20 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_BLAS_TRUE}" && test -z "${COIN_HAS_BLAS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_BLAS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_BLAS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_BLAS_TRUE}" && test -z "${COIN_HAS_BLAS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_BLAS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_BLAS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
